package com.openveil.ui.components

/**
 * Codepoints for the subset Material Symbols font shipped in composeResources.
 *
 * GENERATED by tools/subset_icons.py -- do not edit by hand. To add an icon, add
 * its name to ICONS in that script and re-run it, otherwise the glyph will not be
 * present in the subset font and will render as a blank box.
 */
enum class OpenVeilIcon(val code: Char) {
    Close('\ue5cd'),
    FlashOff('\ue3e6'),
    FlashOn('\ue3e7'),
    FlashAuto('\ue3e5'),
    FlipCameraIos('\uea38'),
    Verified('\uef76'),
    ShieldLock('\uf686'),
    HourglassEmpty('\ue88b'),
    Check('\ue668'),
    CheckCircle('\uf0be'),
    Replay('\ue042'),
    Publish('\ue255'),
    Sync('\ue627'),
    CloudDone('\ue2bf'),
    Public('\ue80b'),
    CloudOff('\ue2c1'),
    PhotoCamera('\ue412'),
    Home('\ue9b2'),
    Person('\uf0d3'),
    Camera('\ue3af'),
    ExpandMore('\ue5cf'),
    ContentCopy('\ue14d'),
    ArrowBack('\ue5c4'),
    IosShare('\ue6b8'),
    Image('\ue3f4'),
    Share('\ue80d'),
    Info('\ue88e'),
    VpnKey('\ue0da'),
    Key('\ue73c'),
    OpenInNew('\ue89e'),
    Link('\ue250'),
    ArrowForward('\ue5c8'),
    Error('\uf8b6'),
    Warning('\uf083'),
    Refresh('\ue5d5'),
    Settings('\ue8b8'),
    InfoI('\uf59b'),
}
